### PR TITLE
Add two more supported functions to README

### PR DESCRIPTION
**Pull request by AlienKevin**

### CODE REVIEW

**Review by adityabakare — COMMENTED** [review]
Have you tested the MiniDP yourself? If you confirm, I'll approve.

**Comment by AlienKevin** [comment]
I confirm as I'm using MiniDP and HDMI right now with two external monitors (both are made by Dell). It even supports configuring monitor layout as I have a landscape display on the left and a portrait display on the right. The experience has been surprisingly smooth so far. With my laptop put aside in closed-clamshell mode, I can't tell whether I'm running on Mac mini or Dell (well, it's a bit exaggerated but you get the idea).

**Comment by adityabakare** [comment]
Good to know! Just make the changes that I requested above and I'll merge the PR.

**Review by AlienKevin — COMMENTED** [review]
I reviewed the changes. However, is this the changes you requested above? (I'm new to PRs)

**Comment by adityabakare** [comment]
No need to review. Just make the requested changes into a new commit. It'll automatically get added over here, and I'll merge.

**Comment by AlienKevin** [comment]
I'm a bit confused. What are the requested changes? 

> Have you tested the MiniDP yourself? If you confirm, I'll approve.

I thought that if I confirm (which I did), you will approve the PR. Maybe I'm missing something here?

**Comment by adityabakare** [comment]
image
image

@AlienKevin

**Comment by AlienKevin** [comment]
Ah! I see what you mean. I managed to make the changes. However, still can't find where you posted the comments.

**Pull request merged**
